### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by g1thubhack3r** [amakerlife/LuoguMsgNotifier#4]
I'm making a GUI wrap of this program.
Could you tell me how to send a message using Python and Websocket?
I will credit you and this program when the first version of the GUI wrap is completed.
你好，我正在编写此程序的图形化封装。
请问你知道如何使用Python和Websocket发送洛谷私信吗？
如果你知道请告诉我，我将会把你和这个程序放到致谢里，谢谢！

**Comment by amakerlife** [comment]
https://0f-0b.github.io/luogu-api-docs/chat#%E5%8F%91%E9%80%81%E7%A7%81%E4%BF%A1 看看这个？

*这个文档不是我写的*

**Comment by g1thubhack3r** [comment]
> https://0f-0b.github.io/luogu-api-docs/chat#%E5%8F%91%E9%80%81%E7%A7%81%E4%BF%A1 看看这个？
> 
> _这个文档不是我写的_

OK, 谢谢！
仓库已经建好了，在[这里](https://github.com/g1thubhack3r/BetterLuoguChat)。
